[theme]
primaryColor="#F63366"
backgroundColor="#E7E1D7"
secondaryBackgroundColor="#F63366"
textColor="#1B78DB"
font="Neue Haas Grotesk Display"
borderColor="#1B78DB"

# For code fonts:
# font="\"Space Mono\":100,400,700|Nunito"
# Base font size:
# baseFontSize=16

[theme.sidebar]
primaryColor="#F63366"
backgroundColor="#ddf1ffff"
#secondaryBackgroundColor="#1B78DB"
textColor="#1B78DB"
font="Neue Haas Grotesk Display"
borderColor="#1B78DB"
