[theme]
primaryColor="#f1cfd8ff"
backgroundColor="#E7E1D7"
secondaryBackgroundColor="#f8d0dbff"
textColor="#1B78DB"
font="Neue Haas Grotesk Display"
borderColor="#1B78DB"

# For code fonts:
# font="\"Space Mono\":100,400,700|Nunito"
# Base font size:
# baseFontSize=16

[theme.sidebar]
primaryColor="#ffe4ecff"
backgroundColor="#ddf1ffff"
#secondaryBackgroundColor="#1B78DB"
textColor="#1B78DB"
font="Neue Haas Grotesk Display"
borderColor="#1B78DB"
